"""empty message

Revision ID: 878f4334ec97
Revises: 87b85cd63cf8
Create Date: 2021-01-20 15:40:37.369295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878f4334ec97'
down_revision = '87b85cd63cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
